---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u9613614/klup.mngdemo.com # Add /<app_folder> if required
    - /bin cp * $DEPLOYPATH #copy all from root
    - /bin/cp -r * $DEPLOYPATH #copy all recursively to $DEPLOYPATH
